### ISSUE TITLE
Approve Design and User Stories for MVP

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#10]
Hi @Katie-Hyde @maggiehoughton , just sorting out final bits so we can start building the initial quick MVP next week 😄 

### **Which design do you prefer?**
Apart from sorting the content (#9) the only other thing we need for this initial MVP we will look to start building next week is to agree which visual design you prefer. To show you what I mean, and the two options, I've recorded a quick video for you (please turn on audio): https://www.loom.com/share/62ec9ed3b944429993a848f14afcb6f1

- [x] Please let me know your preference by leaving a comment in this issue 

### **User Stories**

I have also mapped out the journeys that lay out what we will be building: https://www.figma.com/file/2iSQivVTUotX0WfYfpLj9Y/User-Stories-for-MVP?node-id=0%3A1

They are informed by the prototype (whereas normally you do it the other way round! i.e. map out the journeys before creating wireframes/designs), but I thought it would be useful to use the existing MVP to build these out and we can develop them further in our design work over the coming weeks. 

- [x] Feel free to review and let me know if anything major has been missed, either by comments on this issue or leaving comments in Figma (short video from me on how to do that here: https://www.loom.com/share/246ffbbc6afa498b8d14321bcb7db056 )

**Comment by maggiehoughton** [comment]
Absolutely prefer new colour scheme!

**Comment by thejoefriel** [comment]
Awesome thanks for that @maggiehoughton . I'm going to go ahead and brief the development team so they can get started :)

**Comment by Katie-Hyde** [comment]
Hi all, love the new colors and the change to green once completed, also the tick list function.
