### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#126]
- [x] Log in as admin directs you to homepage, but it should take you to the dashboard
- [x] Log out doesn't work 
- [x] Menu issues
   - [x] Weird gap between edit content and edit details for super-admin menu
   - [x] Log out is a lowercase l 
   - [x] Organisation is missing a s at the end - it should be Organisations
- [x] Internal server error occurs on step 1 of signing up as an organisation when trying to add contact links etc. ```Cannot read property 'name' of undefined``` in use-cases/update-organisation
- [x] Internal server error occurs on step 2 of signing up as an organisation when trying to add logo and colors. ```Column user_id does not exist``` (seems to be a database query error)
- [x] Even though I signed up as an organisation and **shouldn't have access** to edit content, it is in the menu, I can click it and see the page AND I can actually make changes!
- [x] #137
- [x] There's a typo on the top page here. There should be a space between with and hydefoundation
- [x] Even though I signed up as an organisation and **shouldn't have access** to organisations, it is in the menu

**Comment by fadeomar** [comment]
- [ ] dashboard should be updated from the back also to get the correct link!
![image](https://user-images.githubusercontent.com/39485495/131248874-4e126d03-71ab-42fa-9dac-5f7c063040ea.png)
