### ISSUE TITLE
Billing Tasks

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#173]
Hi @maggiehoughton @Katie-Hyde 

We need you please to adding card details to the following platforms: 

- [ ] AWS
- [ ] Heroku
- [ ] Sendgrid

For each one the log in details are here: #1 

Once you do this we can then get the domain set up. 

Also, while you're logging into these accounts, feel free to transfer Sendgrid and Heroku email over to your UCdigital@hyde-housing.co.uk one . But if you change the password, please update the Admin Info spreadsheet. 

Thanks!

**Comment by maggiehoughton** [comment]
@thejoefriel all done- left log ins for now as the reception on this train is shocking!
