### ISSUE TITLE
Switch AWS and Update Sendgrid

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#181]
Hey @RamyAlshurafa AWS is now set up for Hyde with a card and we need to finalise sendgrid. Can you please

- [x] Switch and update the production env vars on heroku
- [x] Update the admin spreadsheet in #1 with the new AWS values for future reference
- [x] Change sender email in Heroku to ucdigital@hyde-housing.co.uk
- [x] Add any other final bits we need to the spreadsheet

Thanks!

**Comment by RamyAlshurafa** [comment]
As agreed with @maggiehoughton to use no-reply@uc-helper.co.uk as sender email to match the domain and prevent it to get blocked
