### ISSUE TITLE
Unauthorized error when admin clicks on Add/update content

### ISSUE THREAD

**Issue by remaininlight** [yalla-coop/universal-credit-support#254]
When an admin clicks on 'Add/update content' in the dashboard they are directed into the main app with an unauthorized error. This doesn't happen for super admins

![Image](https://user-images.githubusercontent.com/4106946/207923362-38b79307-f251-42ac-9656-9e35984e008f.png)

**Comment by cemalokten** [comment]
@RamyAlshurafa Can you help with this?

**Comment by egasparini** [comment]
This functionality should not exist on UC Helper, it was removed in scope of #251
