### ISSUE TITLE
password re-set

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/universal-credit-support#291]
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)

password re-set has been reports through HotJar

![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/1ee9af51-cd31-4822-9f19-4ec5e8f10242)

**Team - do not edit**
@thejoefriel

**Comment by cyberteenie** [comment]
On this as well!

**Comment by RamyAlshurafa** [comment]
Hey @Katie-Hyde 
can you get more details on this, please?
- what is the problem they are countering now? is it the email not being received? or the app crashes?
- what the email address they are using?

**Comment by Katie-Hyde** [comment]
Hi Ramy

Please see attached from Kate regarding the password re-set email

katie

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - can you please forward this to my email at kristina@yallacooperative.com as the forwarded part of your message did not come through. Thank you!

**Comment by RamyAlshurafa** [comment]
Hi @Katie-Hyde 
sorry for the late reply,
Just checked and found that the reset password email has been blocked for "kate.shields@dancefund.co.uk" 
Error message from Sendgrid: "unable to get mx info: failed to get IPs from PTR record: lookup <nil>: unrecognized address".

this means that the domain used (dancefund.co.uk) is not set up correctly, and to solve this they need to:
- check their DNS records set up for dancefund.co.uk. or
- use another email address with a nother valid domain.

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - just wanted to see if we were good to close this issue?

**Comment by Katie-Hyde** [comment]
@cyberteenie i have emailed kate shields with information from ramy

**Comment by Katie-Hyde** [comment]
Yes


Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by cyberteenie** [comment]
Ok great! Thanks Katie.
