### ISSUE TITLE
no access to accounts  - Critical

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/universal-credit-support#292]
- Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)
-

**Describe the bug**
No access to Hyde account for both tools or admin / superuser
![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/e17306e8-69df-440a-8ed6-0fc53545ba71)

**To Reproduce**
1. Go to uc-helper.co.uk .... uc-helper.co.uk/admin ....... col-helper.co.uk/admin and Hyde versions
2. https://col-helper.co.uk/hyde-housing
web capture above

**Expected behavior**
to log on to sites

*Desktop (please complete the following information):**
 - Browser Edge
 -and tried on safari - phone

**

**Team - do not edit**
@thejoefriel

**Comment by Katie-Hyde** [comment]
![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/465f830b-f851-43b6-bab6-0da0b2d89aba)

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - so sorry for the delay on this. We are on it!

**Comment by Katie-Hyde** [comment]
That's done thank you

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by cyberteenie** [comment]
Ah okay, sorry just getting back into the office and sorting out all the bits!
