### ISSUE TITLE
tick boxes on UC helper unresponsive

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/universal-credit-support#294]
you can not tick the tick boxes to say you have completed an action
![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/e4b22bb3-51e6-4dae-a198-387c49bb339b)
this issue is across all organisations tools.
---

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - we are looking into this!

**Comment by Katie-Hyde** [comment]
Thank you

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by cyberteenie** [comment]
@Katie-Hyde also just wanted to mention that you can use the SLA issue templates to report bugs on the app! Thanks!
![Screenshot 2023-09-19 at 15 16 42](https://github.com/yalla-coop/universal-credit-support/assets/97453274/a05519bd-fdc6-41bb-ba24-a3639275524f)

**Comment by RamyAlshurafa** [comment]
Hi @Katie-Hyde 
We have fixed and deployd, can you check please

**Comment by Katie-Hyde** [comment]
Its working again thank you Ramy

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips
