### ISSUE TITLE
unable to access UC helper 

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/universal-credit-support#296]
### Please select the priority level by adding one of the following labels to this issue?

Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)

### Describe the bug and the expected behaviour.

![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/7f4c9cb2-22fe-46f1-becb-93499bf9d720)

unable to access through - edge, chrome and on non work device
states privacy error NET::ERR_CERT_AUTHORITY_INVALID

can not access Hyde's version or admin, I can access Col- helper so it would not seem an issue my end.

### Screenshots or a link to a Loom Recording

![image](https://github.com/yalla-coop/universal-credit-support/assets/87085422/fe165b2b-101f-4942-9c0c-3db28f2eb23b)

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - we are looking into this.

**Comment by RamyAlshurafa** [comment]
Hey @Katie-Hyde 
 seems there was a problem with Domain address SSL certificate, 
the problem seems resolved now, we havent changed anything from our end,
I advice to reach out to your IT team to check on the Domain address provider to get more insight of the issue

**Comment by Katie-Hyde** [comment]
Back in Thank you

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips
