### ISSUE TITLE
Content Discussion

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#34]
@maggiehoughton @Katie-Hyde @jema28 

Spent the past day or so sifting through all the various content links, and actually going through the UC process - up to the point of submitting my claim I think so hopefully won't get in trouble 😅

What I've done is put together a very initial draft that is an iteration on the steps in the wireframes and from the existing journey mapping you had done

https://www.notion.so/Working-out-Content-3453d7d154a444bc9880232715b43e12

**Actions**
- Please let me know what you think - add any comments or notes you like either on the document or in here
- Should we arrange a meeting to talk through properly? Is there time tomorrow that might work?

**Comment by maggiehoughton** [comment]
Let's extend the first session to include this? Both Katie and I are free then.

**Comment by thejoefriel** [comment]
Sure thing @maggiehoughton ! Have done that now

**Comment by maggiehoughton** [comment]
[How to claim Universal Credit _DRAFT.docx](https://github.com/yalla-coop/universal-credit-support/files/6814564/How.to.claim.Universal.Credit._DRAFT.docx)
[Naomi 1 How to claim Universal Credit  - Quick Glance longer.docx](https://github.com/yalla-coop/universal-credit-support/files/6814565/Naomi.1.How.to.claim.Universal.Credit.-.Quick.Glance.longer.docx)
[Naomi 2 - How to claim Universal Credit - quick glance 1 page.docx](https://github.com/yalla-coop/universal-credit-support/files/6814566/Naomi.2.-.How.to.claim.Universal.Credit.-.quick.glance.1.page.docx)

These are good reference docs for anyone who wants to understand process without having to do it.

**Comment by maggiehoughton** [comment]
I've asked one of the welfare specialists to review the content outline above as well- she'll join us at 12.

**Comment by thejoefriel** [comment]
Hey @maggiehoughton I've updated the content document and added in a brief at the top for Catherine. Let me know if anything doesn't make sense
