### ISSUE TITLE
Bug Testing -> MVP

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#45]
This the important phase where you go through the app to make sure it works as agreed and to help us spot remaining bugs (always inevitable unfortunately, especially with brand new products!) 

It is essentially playing with the product pretending you are the different types of users and carrying out all the user journeys / testing the features in the feature plan.  

### App 
https://universal-credit-claim.netlify.app

### Logins 
No log ins needed

### Process
Outline of what you do here: https://www.notion.so/Bug-Testing-6471e3b1c1fe43a9bcb854b22e65952a

### Spreadsheet
Here is where to add all bugs:
https://www.notion.so/de345b449e4746f48bc1b7b805e808d0?v=d4e5a928d7a3457aba2b3e7df03661ce

### Timings
21/07 - 23/07

### Acceptance criteria
- [x] Test the app following the agreed user journeys and features completed for this sprint 
- [x] Add any bugs you come across to this spreadsheet

**Comment by maggiehoughton** [comment]
@thejoefriel Hi there- just an update- we're not finding many bugs, but getting a few suggestions form the team that I don't want to crowd the spreadsheet with. I've added a couple of documents at the end of the Bug Testing document in Notion where I'm just dumping the random comments coming in. It may not be the best place for them so feel free to move!

**Comment by thejoefriel** [comment]
Hey @maggiehoughton thanks for these! Great to hear there weren't any real bugs. I've replied to the couple of things that you and @Katie-Hyde added, but I think we're in a good place to use this tool to test with next week (along with the design prototypes I'm sending shortly) 

One thing that came up in both the comments and also in Katie's feedback using the tool was that you don't actually want to have to tick all the sections to mark it as complete. I'm wondering whether we modify the design so that the button is always at the bottom, and it says 'Mark as complete' rather than 'Next step'. What do you think?

**Comment by Katie-Hyde** [comment]
Hi Joe i was looking at the section on verify identity and found this it seems a bit more user friendly wording for the check list: You’ll definitely need to provide evidence of - could also be taken for the verify part
[uc-checklist.pdf](https://github.com/yalla-coop/universal-credit-support/files/6931381/uc-checklist.pdf)
