### ISSUE TITLE
Build UX Wireframes + Prototypes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#47]
### Link to wireframes

**Prototypes**
- Claimant / Advisor -> https://www.figma.com/proto/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1831%3A1295&scaling=scale-down&page-id=1787%3A3575&starting-point-node-id=1831%3A1295&show-proto-sidebar=1
- Admin -> https://www.figma.com/proto/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1911%3A8102&scaling=scale-down&page-id=1911%3A8101&starting-point-node-id=1911%3A8102
- Super Admin -> https://www.figma.com/proto/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1932%3A9512&scaling=scale-down&page-id=1932%3A9511&starting-point-node-id=1932%3A9512

**Wireframes**
https://www.figma.com/file/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1867%3A12967

Please remember to click the different pages on the left to see each of the wireframes for each user type

### Acceptance
- [x] Build wireframes
- [x] Turn wireframes into prototype
- [x] Make agreed changes following user testing
- [x] Create design system to be used for development 

### Demos
Jem has also put together a couple of videos to take you through as well
- Intro -> https://www.loom.com/share/6f3b02fa8be74c718172794d1e57e728
- Claimants / Advisors -> https://www.loom.com/share/bca58848060845d0a4e2780a1a4e2dc2
- Admin -> https://www.loom.com/share/b7275404efe841e2b770f73e434615bc
- Super Admin -> https://www.loom.com/share/aa18f7866e45440e8640d15d2443c385

**Comment by thejoefriel** [comment]
Hey @maggiehoughton @Katie-Hyde , we can run through these properly in our review meeting, but so you've got a bit of a time before then, here are links to all the new designs. 

What we need from you please on Monday is go through the prototypes and add any comments (using that comment function I showed you). But if you don't get a chance don't worry, we can go through it together on Monday.

Have a great weekend!

**Comment by jema28** [comment]
Hi @maggiehoughton, we've made the changes we went through today. We were wondering if you had any more before testing starts tomorrow? Were you able to go through this afternoon?

**Comment by maggiehoughton** [comment]
I'll have a look now- just working through a google doc of suggested simplified copy. Still can 't open figma on laptop which is very annoying!

Are you able to give me access to the scripts for user testing?

**Comment by maggiehoughton** [comment]
Copy I'm working on is here: https://docs.google.com/document/d/1ud2-bE56k5wQbh8lL45M3WHU67r07zQXrIQlBOt3t5I/edit?usp=sharing

**Comment by jema28** [comment]
Hi @maggiehoughton, I've double checked the link, can you try again: https://www.notion.so/User-Testing-371fc29628f542aa8e021a5be51af3f8? 

You can open the prototype using Figma Prototype app on your phone. Let me know if you can find it? 

Thanks for the document!

**Comment by jema28** [comment]
Hey @maggiehoughton I'm going to look through this tomorrow morning. Could you message here when you're finished? Thanks!

**Comment by maggiehoughton** [comment]
I can access scripts now- thanks!

I'm more or less done with first run through of copy- my brain is done at least. I suspect we'll get comments re the copy from users as well so there will be more to update later:-)

**Comment by jema28** [comment]
Hi @maggiehoughton, thanks for the document! I double checked everything was the same this morning. Definitely :) I've got a few questions regarding the prototype:

1. Which partner logos do you want on the admin pages?
<img width="546" alt="Screenshot 2021-07-27 at 06 22 17" src="https://user-images.githubusercontent.com/25960351/127100107-d62fc400-56e2-4a02-8548-89b2c3d708b0.png">
2. If we wanted to add a mobile bank to the bank account advice. Not sure if that makes things more complicated though.
<img width="605" alt="Screenshot 2021-07-27 at 06 24 27" src="https://user-images.githubusercontent.com/25960351/127100181-1c51f41e-0230-4b7e-9110-087bce94c2d9.png">
3. I've also asked Joe on this but can't remember what we landed on regarding the government helpline? Did we want the checkbox added?
<img width="609" alt="Screenshot 2021-07-27 at 06 25 24" src="https://user-images.githubusercontent.com/25960351/127100278-72f51297-8fbe-4d97-b503-962fe1fcd9d1.png">

**Comment by maggiehoughton** [comment]
HI there

1. I assume there are guidelines from Catalyst- I can check. I think Lottery, Hyde, Catalyst and yours (if you want)? 
2. Could you say 'You can set up a free bank account with most high street and online banks' (we can't really recommend one)
3. I think we scrapped check box as could not think of why other wouldn't want it.

**Comment by thejoefriel** [comment]
> Copy I'm working on is here: https://docs.google.com/document/d/1ud2-bE56k5wQbh8lL45M3WHU67r07zQXrIQlBOt3t5I/edit?usp=sharing

Thanks so much for creating this @maggiehoughton - was working on this but you beat me to it! 😄

**Comment by jema28** [comment]
Hi Maggie, 

I hope you've had a nice weekend!

Regarding no 1 we can sort this for the next round of wireframes. Let me know?

We updated the text to "This should be the bank account that your UC will be paid into. You can set up a free bank account in most high street banks or an online bank if you don’t already have one" in the prototype but I can't edit the word doc. Would you mind editing it or giving us edit access? Thanks!

Okay sure thing re no 3.

**Comment by thejoefriel** [comment]
Have created an updated version of the content doc for us to work on

https://docs.google.com/document/d/1Fq7vB5LZW8lachRyZZcPg9_ZDaYsmHxEaOv_somyf6s/edit

**Comment by maggiehoughton** [comment]
@thejoefriel @jema28 I've made some suggestions on the copy- too many to log them all in the bug sheet. Is there a simple way of updating the copy directly in the app?
