### ISSUE TITLE
Updates + User Testing - Round 2 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#49]
**Link to synthesised user feedback**
https://www.notion.so/UX-Testing-Feedback-0e186f12c72c4955916b05a87ad09eaf

**Key Things to check with user testing**
Overall for UX and layout there aren't many things to test (I've labelled them as 'need to test' in the Synthesised Changes table. These are purely for claimants really so I'd suggest we only do testing with claimants next week 

The main changes are actually the content. Overall the content style was positively received, so we are in a good space with the style. 
However, there was lots of feedback from advisors as to:
- extra tips to add
- extra items in check list to add 

My suggested approach to implement these changes
- [x] 6/08 - Yalla & Hyde to do a review of all the elements that say copy review and make the changes together in our word document. We would do this in our wireframe review meeting
- [x] Hyde to circulate with the internal team and get everyone to add comments by 10/08
- [x] 10/08 - We then do a final content review session to determine which bits to implement 

**Proposed approach**
- [x] Get content finished following the approach outlined above by 10/08
- [x] 11/08-12/08 - Carry out testing with 3-5 claimants to get feedback on the UX and content changes
- [x] 13/08 - Final review as planned ahead of development

**Comment by thejoefriel** [comment]
Hey @Katie-Hyde @maggiehoughton - here's my suggested approach for delivering the changes from user feedback and what level of testing to do next week. Let me know what you think?

**Comment by jema28** [comment]
Hey @Katie-Hyde, I hope you're well! I was wondering if you had access to our notion? As I tried to @ you this morning but you weren't coming up. Could I have your email address? I think it should work once I invite you

**Comment by Katie-Hyde** [comment]
Hi Jem

My email is ***@***.******@***.***> but I also have access to notion - Hyde + Yalla Workspace (notion.so)<https://www.notion.so/Hyde-Yalla-Workspace-a96ed911c5ae413e9764fe7b2b1efa01>

Not sure what I have been entered as.

Katie


Katie Ford
Senior Advisor Successful Tenancies


T: 01243 816943 (Ext. 16943)
M: 07918 768 587
E: ***@***.******@***.***>

Hyde Foundation • Martlet House • Southern Gate • Chichester • PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> • Facebook<http://www.facebook.com/HydeGroup> • LinkedIn<http://www.linkedin.com/company/the-hyde-group> • YouTube<http://www.youtube.com/user/TheHydeGroup?feature=watch>


MyAccount - manage your account online anywhere, anytime<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hyde-housing.co.uk%2Ftenants%2Fmyaccount%2F&data=04%7C01%7Ckatie.ford%40hyde-housing.co.uk%7C8cfd49d71c3d40cc4d7708d870ddbbbc%7C86819931fb92466f8ad749b48fb5a50d%7C0%7C0%7C637383444922347086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0SnSvhLnvsD9WBy0HWyqB9T1L1PSM2z9kt7LqsxDag4%3D&reserved=0>

**Comment by Katie-Hyde** [comment]
@thejoefriel HI Joe confirmed content for the claiming UC as a couple for the tool with an advisor but also on gov.uk it states 
If you are part of a couple you and your partner will need to make a joint claim for Universal Credit.
You begin by creating a Universal Credit online account each. The first person to create their account will be given a partner code, which will be displayed on screen. 
This code will need to be input by your partner when they register for their Universal Credit online account. This ensures the accounts are joined together and you are correctly claiming as a couple.
so to make easier i would put:
If you have a partner you will need to make a joint claim. To do this one person claims first stating they have a partner and will be given a partner linking code. When your partner claims they then input the linking code when they say they have an account to link to.

**Comment by Katie-Hyde** [comment]
@thejoefriel can you let me know if the above link is ready to send to staff for further comment
