### ISSUE TITLE
Add new icons to Icon component

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#59]
Use the existing Icon component, this is just adding further icons.

__Wireframe link__

https://www.figma.com/file/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=2482%3A45090

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Add new icons
- [x] Include icon with text
- [x] Replace Hyde logo with the svg we have in Figma

**Comment by fadeomar** [comment]
` Include icon with text;`
it would be much better to use the Icon component from our Projects with Typography component instead of customizing the Icon component to accept text!

**Comment by thejoefriel** [comment]
Happy either way @fadeomar  :)

**Comment by fadeomar** [comment]
I've create new component `TextWithIcon` it covers : 
  - external links with icon
  - internal links with icon 
  - normal text with icon

**Comment by thejoefriel** [comment]
sounds good 👍
