### ISSUE TITLE
Recruit People for User Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#8]
**Summary**
This issue is to track our discussion and progress recruiting people for user testing. 

**Who we want to test with?**
- Claimants
- Advisors
- Administrators

**Dates for user testing**
- w/c 26th July
- w/c 9th August (optional based on first round of feedback)
- w/c 30th August

**Actions**
Here's the current plan we're agreed 
- [ ] Yalla to send across potential questions to include in survey
- [ ] Hyde to send out survey and feedback with those potentially interested
- [ ] Yalla to then reach out and arrange the interviews

## Useful links

- **Explanation about user testing - what it is and how it works** -> https://www.notion.so/User-Testing-852be476a6304069ae445f005084f3cd

**Comment by thejoefriel** [comment]
## Questions to include in the survey

Hi @Katie-Hyde @maggiehoughton from looking at the documentation and research you've done so far, it seems like we have asked them questions on UC already. So I was largely thinking about questions that might help us research user experiences they typically enjoy to inform out thoughts on content style and overall user experience with flows. 

Here are some potential questions I'm thinking:

- What websites or apps do you use the most for entertainment?

- What websites or apps do you use the most for information or learning?

- What websites or tools have you used when looking for information about subjects like jobs or managing money?
- - What do you like or dislike about these? (this same question could be asked as a follow up on the other questions too, but might be a bit too much) 


What do you think? Any others you think would be useful to know based on learnings from your Discovery work?
Also, two questions for you:
- do we know they fit our personas based on who you're sending it out to or do we need to ask anything to fine-tune that?
- do we need to ask whether they have ever tried / are currently trying / plan to try applying for UC?

## Offer

To confirm, we're happy to offer £30 for each user testing session, using the voucher you recommended

**Comment by thejoefriel** [comment]
Hey @jema28 just on this, are there any other questions you think would be helpful from a landscaping perspective?

**Comment by jema28** [comment]
Hey @thejoefriel, I think having an idea of the 1 - 2 learning websites/apps they would pick in terms of UX (functionality) and UI (look/feel of the app) would be really helpful. Particularly:

1. What do you like about a certain flow in particular? It is the clarity, the ease of use, the experience of going through or another point? 
2. On the user interface side of things, are there any colours that stand out/you like? Any graphics or icons? Is it the layout that you prefer? 
3. What makes you come back to the site/app(s)? 
4. What are the key things you're looking for in a learning app?

**Comment by maggiehoughton** [comment]
Thanks for input- I think we need to keep it very simple to get residents through to the crucial final question (about helping with user testing).
I am thinking we do two strands (we'll get help from survey team to formulate the exact questions)- 

First question (y/n) is whether they have claimed or not (we will only send survey to those who we know have recently claimed, or who will need to claim in the next 2 years)

If y: 
1) How easy did you find claiming UC online (this would be to help us filter potential candidates for user testing- we want those who found it difficult)
2) What was most difficult? (tick list)
3) what are favorite web pages / apps ( limited free text- up to 3)
4) a/b/c/ For each- what do you like about them (tick list)
5) Would you be happy to help us by participating in user testing?


If n):
1) How confident are you about claiming UC online (this would be to help us filter potential candidates for user testing- we want this not very confident)
2) what do you currently use the internet for (tick list)
3) what are favorite web pages / apps ( limited free text- up to 3)
4) a/b/c/ For each- what do you like about them (tick list)
5) Would you be happy to help us by participating in user testing?

**Comment by thejoefriel** [comment]
Hi @maggiehoughton this sounds good! For what you like about them, rather than tick list it might be also good just to leave it open text, but if you feel that's too overwhelming then ticking from options would be fine. Would you want us to write up those options for you?

Also, just to confirm on the final question, we will be providing a quick explanation of what 'user testing' is and include the mention of the financial incentive right? Again, on this, let me know if you want me to write up a draft of that explanation.

**Comment by maggiehoughton** [comment]
It would be great if you can help us write the tick lists, and the content for the user testing bit- thanks!

**Comment by thejoefriel** [comment]
Thanks @maggiehoughton , been working on this and put together the following draft. Let me know your initial thoughts. 

**List**
- Looks great
- The content is engaging
- It is informative / useful
- Easy to use
- It’s got personality
- There are fun pictures / videos on it
_Optional if we wanted to leave room for a free text input_
- Any additional info to add? A short sentence explaining why would be great!

**Info about user testing**
User testing is basically a short conversation (between 30 to 60 minutes depending on how much time you have) where we will ask you to try out an online tool we’re building that we hope you will find useful. There’s nothing you need to prepare and it is very relaxed. For your help we will give you a £30 [INSERT TYPE] voucher

**Comment by thejoefriel** [comment]
Hi @maggiehoughton @Katie-Hyde  was thinking about this more and thought about this?

"When using a website to find help with something (e.g. saving money, paying bills) which of these things make for a good experience for you?'
- It uses lots of images 
- It uses lots of videos
- It is easy to move around the website and work out way to go 
- It's got a bit of personality
- There's not lots of words 
- Content is kept simple
- Everything is one place rather than clicking around
- It looks good
- Anything else not covered above? 

If you like we could also make the question broader so "When using a website what makes it a good experience for you" - although I think it'd be great to narrow it down a bit if possible. 

Is this more in line with what the team were thinking?

**Comment by thejoefriel** [comment]
Hey @maggiehoughton , I just wanted to check that the survey has now been sent out?

**Comment by maggiehoughton** [comment]
We are waiting for the data set (recipients). I'll chase now. I had some comments to make about the draft I've seen as well- will try to share. We're aiming to have it out by COB Friday, the thinking is that those who complete it will do so straight away, and not sit on it.

**Comment by maggiehoughton** [comment]
Can I check how many & what functions you would like in terms of advisor/ income officer/ administrator user testing? I can get these lined up now?

**Comment by thejoefriel** [comment]
Thanks for the update @maggiehoughton - all sounds good. We can then review on Monday and see where we are :) 

In terms of other users I'd say:
- Advisors -> ideally 5 (a mix of Alex's and Sophie's would be great)
- Income Officers -> ideally 5 (a mix of Carolines and Thomas's would be great) 
- Administrators -> I think probably 3-5 would be sufficient. You and Katie already fall into this set, so I reckon 3 - 5 of people in other potential organisations so we can test what it's like coming on fresh, that would be great! 

If you send me emails I'm very happy to do approaches. Whatever is best / easiest for you
