### ISSUE TITLE
Send over provisional content for the MVP

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#9]
**Summary**
We need to see all the provisional content required to help guide our users in the UC process. This will then help us:
- Think further about how to shape as part of our design sprint
- Get initial content in the first digital iteration we are looking to build next week for some early user testing

**Actions** 
- [ ] Hyde to send over provisional content

**Comment by maggiehoughton** [comment]
Katie pulled together a great list of examples of checklists/ guides- can work out how to attach doc to this so will email separately.

**Comment by Katie-Hyde** [comment]
[content links research.docx](https://github.com/yalla-coop/universal-credit-support/files/6790855/content.links.research.docx)

**Comment by maggiehoughton** [comment]
Just from Katie's list (once you get it), the entitled to & CAB guides are probably the best to go to at this phase as they are short and basic.

**Comment by thejoefriel** [comment]
Amazing, thanks for this @Katie-Hyde @maggiehoughton ! I've given them a quick initial look over and will now go in depth to see how this can be provisionally broken out into the steps you got to from the discovery work (and whether we need to include additional steps)

The first link though (the citizens advice one) is broken for me. It looks like a PDF so are you able to maybe upload the PDF here instead please?

**Comment by Katie-Hyde** [comment]
[UC-checklist-applying.pdf](https://github.com/yalla-coop/universal-credit-support/files/6791296/UC-checklist-applying.pdf)
